### PR TITLE
FEAT: support kserve with authorino

### PR DESCRIPTION
**Pull request by aslakknutsen**
* Activate extauth for grpc traffic
* Set host on requests from activator to trigger authconfig
* Temp Authorization header fix to workaround https://issues.redhat.com/browse/OSSM-4873

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@aslakknutsen how can I test it?

**Comment by aslakknutsen** [comment]
Not much to test beyond that they get installed. This depends on a few other PRs coming elsewhere

**Comment by aslakknutsen** [comment]
You can always setup a echo service on port 8013 with label "component: predicator" and;

* call it by ip and use header k-original-host with a host name and see it end up as Host in the echo request
* call something that's "pass_through" in extAuth with an Authorization header and see it's still there when it reach the target

**Comment by bartoszmajsak** [comment]
As for the linter errors, I will soon push cleanup to the target branch so we will see if there's anything left in your PR

**Comment by bartoszmajsak** [comment]
Closes, as it's been reworked in #13

**Pull request closed without merging**
